# Generated by Django 5.0.2 on 2026-06-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
